---
  
- name: Install CloudWatch libraries
  apt: name={{ item }} state=installed
  with_items:
    - libwww-perl
    - libdatetime-perl
- name: Checking if cloudwatch already Downloaded to this machine
  stat: path=~/root/aws-scripts-mon
  register: cloudwatch_folder

- name: download scripts
  get_url: url=http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip dest=/tmp/CloudWatchMonitoringScripts.zip
  when: not cloudwatch_folder.stat.exists

- name: chown the file and make it writeable
  file: path=/tmp/CloudWatchMonitoringScripts.zip mode=0755  #owner=ubuntu group=ubuntu 
  when: not cloudwatch_folder.stat.exists

- name: unzip the scripts
  # note - unarchive should work but it fails; maybe an ansible issue?  shell: to the rescue!
  #unarchive: src=/tmp/CloudWatchMonitoringScripts.zip dest=/tmp/
  shell: "cd /tmp && unzip /tmp/CloudWatchMonitoringScripts.zip"
  when: not cloudwatch_folder.stat.exists

- name: delete archive
  file: path=/tmp/CloudWatchMonitoringScripts.zip state=absent
  when: not cloudwatch_folder.stat.exists

- name: set Access key in credentials file
  replace: dest=/tmp/aws-scripts-mon/awscreds.template regexp='AWSAccessKeyId=' replace='AWSAccessKeyId={{ ec2_access_key }}' backup=yes
  when: not cloudwatch_folder.stat.exists

- name: set Secret key in credentials file
  replace: dest=/tmp/aws-scripts-mon/awscreds.template regexp='AWSSecretKey=' replace='AWSSecretKey={{ ec2_secret_key }}' backup=yes
  when: not cloudwatch_folder.stat.exists

- name: move directory out of /tmp
  command: mv /tmp/aws-scripts-mon/ /root/ creates=/root/aws-scripts-mon/
  when: not cloudwatch_folder.stat.exists

- name: add command to cron
  lineinfile: dest=/etc/crontab insertafter=EOF line="*/5 * * * * root /root/aws-scripts-mon/mon-put-instance-data.pl --mem-util --mem-used --mem-avail --swap-util --swap-used --disk-path=/ --disk-space-util --disk-space-used --disk-space-avail --aws-credential-file=/root/aws-scripts-mon/awscreds.template"
  when: not cloudwatch_folder.stat.exists
